### ISSUE TITLE
Setup_retropie.sh doesn't work

### ISSUE THREAD

**Issue by Miity-games** [JohSchneider/piboy-zero#2]
When installing the pi bij flashing RetroPie connecting it and following the installation guide the command ./setup_retropie.sh doesn't work and can't be found what am I doing wrong?

**Comment by JohSchneider** [comment]
well first of all thank you! for giving this a try - after all this time
did you also/actually build the whole "hardware"?

i guess running the script itself from the directory it lives in isn't actually the problem (?)
but more likely that after five years the retro-pie distro i tried this against has changed enough that this helper-script doesn't really apply or help much anymore :-s 

so you might be better of running it's content step by step - and always question if it still applies to a current release of retropie = take it as a (dated) guide, not a turn key solution (it once was)

**Comment by Miity-games** [comment]
I guess I've downloaded the newest RetroPie I'll try 4.1 tonight and let u updated
Thanks for the fast response

**Comment by Miity-games** [comment]
Pi zero 2 doesn't load the 4.1 images sadly I will put some work in it trying to make it work
